version: "3.9"
services:
  opencap-dev:
    image: opencap-dev
    #cpuset: '0'
    volumes:
      - data:/data
    env_file:
      - ../.env
    environment:
      - DOCKERCOMPOSE=1
    deploy:
      resources:
<<<<<<< HEAD
        #limits:
          #cpus: '24.0'
          #memory: 20G
=======
        limits:
          cpus: '8.0'
>>>>>>> 4cce2732fdfadb64a534a4879de7a86b3bbc8145
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  openpose-dev:
    image: openpose-dev
    #cpuset: '0'
    volumes:
      - data:/openpose/data
    deploy:
      resources:
<<<<<<< HEAD
        #limits:
          #cpus: '24.0'
          #memory: 20G
=======
        limits:
          cpus: '8.0'
>>>>>>> 4cce2732fdfadb64a534a4879de7a86b3bbc8145
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  mmpose-dev:
    image: mmpose-dev
    #cpuset: '0'
    volumes:
      - data:/mmpose/data
    deploy:
      resources:
<<<<<<< HEAD
        #limits:
          #cpus: '24.0'
          #memory: 20G
=======
        limits:
          cpus: '8.0'
>>>>>>> 4cce2732fdfadb64a534a4879de7a86b3bbc8145
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  data: {}
